FROM centos:7

# needed for pidof used in hidra.sh
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* \
    && sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* \
    && yum install -y sysvinit-tools psmisc

# needed for status used in hidra.sh
COPY initfunctions.sh /etc/rc.d/init.d/functions

COPY datamanager_p00.yaml /conf/datamanager_p00.yaml

RUN mkdir -p /var/log/hidra && chmod 777 /var/log/hidra \
    && mkdir -p /opt/hidra && chmod 777 /opt/hidra

ARG user_uid

RUN adduser --uid $user_uid hidra

WORKDIR /hidra
