FROM debian:9

COPY *deb9*.deb /debs/


# Fix archived repositories:
# https://www.geekersdigest.com/apt-etc-apt-sources-list-for-every-debian-release/
RUN echo "\
    deb http://archive.debian.org/debian/ stretch main contrib non-free\n\
    deb http://archive.debian.org/debian/ stretch-proposed-updates main contrib non-free\n\
    deb http://archive.debian.org/debian-security stretch/updates main contrib non-free" \
    > /etc/apt/sources.list

RUN apt update && apt install -y systemd python-watchdog /debs/*

# setup systemctl-replacement-script
COPY systemctl.py /bin/systemctl
RUN chmod +x /bin/systemctl

COPY datamanager_p00.yaml /conf/datamanager_p00.yaml

ARG user_uid

RUN adduser --system --uid $user_uid hidra

WORKDIR /hidra

# Workaround for segfault in apt install -y ./build/debian9/...
# See https://unix.stackexchange.com/a/227636
# and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=753941
RUN echo "APT::Cache-start 200000000;" > /etc/apt/apt.conf.d/00bugs