FROM yakser/opensuse-64:10.2

COPY timeout /usr/local/bin/timeout

RUN chmod +x /usr/local/bin/timeout

COPY datamanager_p00.yaml /conf/datamanager_p00.yaml

RUN mkdir -p /var/log/hidra && chmod 777 /var/log/hidra \
    && mkdir -p /opt/hidra && chmod 777 /opt/hidra

ARG user_uid

RUN useradd --uid $user_uid hidra

WORKDIR /hidra

CMD bash
