read-write_file_r_c: read-write_file_r.c
	gcc -o read-write_file_r.x -ggdb read-write_file_r.c -lzmq -ljson-c -I/usr/include/json-c/

read-write_file_w_c: read-write_file_w.c
	gcc -o read-write_file_w.x -ggdb read-write_file_w.c -lzmq -ljson-c -I/usr/include/json-c/
