FROM centos:7

ADD desy-common_sl7.repo /etc/yum.repos.d/desy-common.repo
RUN yum update -y && \
    yum install -y wget \
    epel-release \
    rpm-build \
    gcc \
    python-devel
RUN yum install -y \
    zeromq-devel
RUN cd && \
    wget https://pypi.python.org/packages/af/37/8e0bf3800823bc247c36715a52e924e8f8fd5d1432f04b44b8cd7a5d7e55/pyzmq-16.0.2.tar.gz#md5=9a8768b00a566a400d70318f8c359cfe && \
    tar -xf pyzmq-16.0.2.tar.gz && \
    rm pyzmq-16.0.2.tar.gz && \
    mv pyzmq-16.0.2 python-zmq-16.0.2 && \
    tar -cvzf python-zmq-16.0.2.tar.gz python-zmq-16.0.2 &&\
    mkdir -p /root/rpmbuild/SOURCES && \
    mv python-zmq-16.0.2.tar.gz /root/rpmbuild/SOURCESyum  && \
    cd python-zmq-16.0.2 && \
    python setup.py bdist_rpm --spec-only && \
    mkdir -p /root/rpmbuild/SPECS && \
    mv dist/pyzmq.spec /root/rpmbuild/SPECS/python-zmq.spec && \
    sed -i "s/pyzmq/python-zmq/" /root/rpmbuild/SPECS/python-zmq.spec && \
    rpmbuild -ba /root/rpmbuild/SPECS/python-zmq.spec
