FROM debian:buster

RUN apt update && apt install -y \
    lsb-release \
    dpkg-dev \
    debhelper \
    python \
    dh-python \
    python-dev \
    python-setuptools \
    python3 \
    python3-dev \
    python3-setuptools
