FROM centos:7

# Fix archived repositories
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && \
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

RUN yum update -y && yum install -y \
    git \
    rpm-build \
    python-devel \
    python-setuptools \
    python3-devel \
    python3-setuptools
