FROM ubuntu

RUN apt update && apt install -y \
    git \
    python \
    python-pip
RUN pip install --upgrade pip && pip install \
    pyzmq
RUN cd /opt && git clone https://stash.desy.de/scm/hidra/hidra.git
RUN cd /opt/hidra && git checkout develop
RUN cp -r /opt/hidra/src/APIs/hidra /usr/local/lib/python2.7/dist-packages/
