FROM ubuntu

RUN apt update && apt install -y \
    python3 \
    python3-zmq \
    python3-setproctitle \
    python3-six \
    python3-yaml \
    python3-logutils \
    python3-kafka
ENTRYPOINT ["python3", "/opt/hidra/src/sender/datamanager.py", "--verbose", "--config_file", "/opt/hidra/conf/datamanager_ewmscp.yaml", "--onscreen", "debug"]
