FROM ubuntu

RUN apt update && apt install -y \
    git \
    python3 \
    python-pip
RUN pip install future pyzmq pyyaml ldap3
RUN cd /opt && git clone https://github.com/hidra-org/hidra.git
# RUN cd /opt/hidra && git checkout develop
RUN PYTHON_VERSION=$(ls /usr/local/lib/ | egrep 'python3.*') && cp -r /opt/hidra/src/api/python/hidra /usr/local/lib/PYTHON_VERSION/dist-packages/
